### PR TITLE
Added Linked Lists Operations using C++

### PR DESCRIPTION
**Pull request by Zanark**
Added a README for the folder too.

### CODE REVIEW

**Comment by Zanark** [comment]
@StaneCobalt  I added Heap Sort too.

**Comment by Zanark** [comment]
Okay will do that

**Comment by Zanark** [comment]
@StaneCobalt I made the changes. Please review.

**Comment by Zanark** [comment]
@StaneCobalt please review

**Comment by StaneCobalt** [comment]
Awesome! Merged :wink:

**Pull request merged**
