### PR TITLE
Added few algorithms in java and python

### LINKED ISSUE #45: Shell Sort
Shell Sort is not included

### PR DESCRIPTION
**Pull request by salif-04**
Fixes #45 
Java:
Insertion Sort
Merge Sort
Selection Sort
Quick Sort

Python:
Quick Sort
Shell Sort

### CODE REVIEW

**Comment by StaneCobalt** [comment]
Very nice, if you can rename the files to match our camel case naming scheme I'll merge them in! If any of your files has a naming conflict with an existing file, just add a number to then end of the name! 😄

**Comment by salif-04** [comment]
Sure.

**Comment by salif-04** [comment]
Done the changes.

**Comment by StaneCobalt** [comment]
Thank ya sir, merged it :smiley:

**Pull request merged**
